name: prettier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '33 23 * * 5'

jobs:
  run_eslint:
    name: MessageQuote prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install
      - name: Prettier#check
        run: yarn run check
